version: "3"
services:

  imgserver:
    image: imgserver
    container_name: imgserver
    networks:
      - test-network
    ports:
      - 8080:8080
    volumes:
      - /home/server_images:/go/src/goimg/img

networks:
  test-network:
    driver: bridge
