version: "3"
services:

  imgserver:
    image: imgserver
    container_name: imgserver
    networks:
      bridge
    ports:
      - 8080:8080
    volumes:
      - /home/server_images:/go/src/goimg/img

networks:
  default:
    driver: bridge

